import = ["/home/seha/.config/alacritty/tokyonight_storm.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 750
unfocused_hollow = true

[cursor.style]
blinking = "On"

[font]
size = 12

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro"
style = "Bold Italic"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000
multiplier = 3

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
opacity = 0.9

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5
