##################################################

window:
  padding:
    x: 10
    y: 10

  class:
    instance: Alacritty
    general: Alacritty

  decorations: full

  dynamic_title: true
  dynamic_padding: true

##################################################

scrolling:
  history: 100000
  multiplier: 3

##################################################

font:
  normal:
    family: Source Code Pro
    style: Regular

  bold:
    family: Source Code Pro
    style: Bold

  italic:
    family: Source Code Pro
    style: Italic

  bold_italic:
    family: Source Code Pro
    style: Bold Italic

  size: 9

##################################################

draw_bold_text_with_bright_colors: true

##################################################

cursor:
  style:
    blinking: On

  blink_interval: 750

  unfocused_hollow: true

##################################################

live_config_reload: true

##################################################

import:
  - ~/.config/alacritty/dracula.yaml

##################################################

mouse:
  hide_when_typing: true

##################################################

